//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUNLER
    {
        public int URUNID { get; set; }
        public string URUNADI { get; set; }
        public int URUNKATEGORI { get; set; }
        public Nullable<decimal> FİYAT { get; set; }
        public string MARKA { get; set; }
        public Nullable<byte> STOK { get; set; }
    
        public virtual KATEGORILER KATEGORILER { get; set; }
    }
}
